### ISSUE TITLE
Error whil authservice inititaliztion

### ISSUE THREAD

**Issue by smfaizalkhan** [witcom-gmbh/keycloak-authz-angular#1]
zone.js:3243 POST http://localhost:8080/auth/realms/VMS/protocol/openid-connect/token 400 (Bad Request)
The response was client secret not provided in request
![image](https://user-images.githubusercontent.com/22238550/62426152-7fd3e200-b6e1-11e9-9060-18b8e8e26d94.png)

So i checked in postman passing authtoken 

![image](https://user-images.githubusercontent.com/22238550/62426162-a560eb80-b6e1-11e9-9f50-1d969ce38ef3.png)

![image](https://user-images.githubusercontent.com/22238550/62426165-ae51bd00-b6e1-11e9-8de9-a5a765af4bde.png)

Checked the response token and i see the list of resources and scopes

![image](https://user-images.githubusercontent.com/22238550/62426175-d0e3d600-b6e1-11e9-9920-3952d3ea8305.png)

can you provide an example ?

**Comment by smfaizalkhan** [comment]
Hi,
I added a HttpInterceptor,added in app module provider and thereby added the token ,so now i get back an rpt token

 {
      provide: HTTP_INTERCEPTORS,
      useClass: TokenInterceptor,
      multi: true
    }

constructor(private auth: KeycloakService) {
  }



  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

    const tokenPromise: Promise<string> = this.auth.getToken();
    const tokenObservable: Observable<string> = from(tokenPromise);


    return tokenObservable.pipe(
      map(authToken => {
        console.log('authtoekn',authToken);
        req = req.clone({setHeaders: {Authorization: 'Bearer ' + authToken}});
      }),

      concatMap(request => {
        return next.handle(req);
      }));

  }
I dont know if tis part of the api,But it would be better to be a part of the api.

**Comment by iceman91176** [comment]
Hi,
no additional HTTP_INTERCEPTOR  is required when using the [keycloak-angular](https://github.com/mauriciovigolo/keycloak-angular#httpclient-interceptor) plugin, since that plugin adds the bearer token automatically.
The keycloak-authz-angular plugin is an extension to the keycloak-angular library - it is not intended to work standalone.
HTH

**Comment by iceman91176** [comment]
Closing this, repo is not maintained any more
